### ISSUE TITLE
Need to add .gitignore file

### ISSUE THREAD

**Issue by IlyaDovzhenko** [rmgooogle/KishMan#3]
Need to add .gitignore file and close this issue

**Comment by IlyaDovzhenko** [comment]
Link example:
https://github.com/IlyaDovzhenko/spring5-jokes-app/blob/master/.gitignore

**Comment by IlyaDovzhenko** [comment]
Example don't have ignore path to /out package. Add it!

**Comment by IgorPolyakov** [comment]
сорян шо на русском
таки да, `/out` желательно добавить в файл `.gitignore`
а артефакты сборки `KishMan/out/production/PACMAN/` лучше удалить из проекта
почитать мжно тут https://git-scm.com/book/ru/v2/%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D1%8B-Git-%D0%97%D0%B0%D0%BF%D0%B8%D1%81%D1%8C-%D0%B8%D0%B7%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B9-%D0%B2-%D1%80%D0%B5%D0%BF%D0%BE%D0%B7%D0%B8%D1%82%D0%BE%D1%80%D0%B8%D0%B9

**Comment by rmgooogle** [comment]
> сорян шо на русском
> таки да, `/out` желательно добавить в файл `.gitignore`
> а артефакты сборки `KishMan/out/production/PACMAN/` лучше удалить из проекта
> почитать мжно тут https://git-scm.com/book/ru/v2/%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D1%8B-Git-%D0%97%D0%B0%D0%BF%D0%B8%D1%81%D1%8C-%D0%B8%D0%B7%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B9-%D0%B2-%D1%80%D0%B5%D0%BF%D0%BE%D0%B7%D0%B8%D1%82%D0%BE%D1%80%D0%B8%D0%B9

Спасибо, что на русском )
